### ISSUE TITLE
Can I find the previous state after event happened?

### ISSUE THREAD

**Issue by harryworld** [DenTelezhkin/Transporter#1]
I know the array of possible source events. Is it possible to get the exact previous state?

Thanks

**Comment by DenTelezhkin** [comment]
Hey!

There's no built-in functionality like this, since it's uncommon for finite state-machines to store previous states, however you can easily achieve this by using event blocks such as

``` swift
shouldFireEvent(_:)
willFireEvent(_:)
```

And storing current state machine state in your own property.

**Comment by harryworld** [comment]
Thanks for that, I think `currentState` before firing event is what I should look at.
