### ISSUE TITLE
Destination states based on logic?

### ISSUE THREAD

**Issue by smebberson** [DenTelezhkin/Transporter#2]
Hey does Transporter support switching destination states based on logic in a function?

**Comment by DenTelezhkin** [comment]
Hey!

It depends on how you define logic or a function =) Transporter has ability to switch to destination state based on Event, which itself can have some logic, and has shouldFireEvent block, that can be used to determine whether Event should be fired.

Basically, i try to stay true to original concept of state machine and keep it very simple. Does that answer your question?

**Comment by smebberson** [comment]
A great answer. Thanks! Made me see things slightly differently, and more cleanly :)
