### ISSUE TITLE
'ErrorProtocol' has been renamed to 'Error'

### ISSUE THREAD

**Issue by aperritano** [DenTelezhkin/Transporter#3]
Hi, Xcode beta 5 comes up with these errors

![untitled](https://cloud.githubusercontent.com/assets/219031/17650773/cc44f232-621b-11e6-80c1-3892da9d6033.png)

**Comment by DenTelezhkin** [comment]
Hey!
Thanks for reporting, I've pushed updates to swift3 branch.
