### ISSUE TITLE
shouldFireEvent closures should support asynchronous calls

### ISSUE THREAD

**Issue by tidyware** [DenTelezhkin/Transporter#5]
It appears that shouldFireEvent needs to return true / false immediately when called.

Is there a way for a shouldFireEvent closure to return true / false after executing asynchronous code?

**Comment by DenTelezhkin** [comment]
I believe it's the nature of state machine to be synchronous. If you need asynchronous transformations, i believe it's better to use abstraction like Rx, where you can wrap your event in Observable.

Right now Transporter does not support asynchronous callbacks, unfortunately.

**Comment by tidyware** [comment]
Thank you for the reply.

I think it would make sense to allow a transition to complete or not based on the results of an asynchronous call. Until a promise (or similar mechanism) is resolved with success or reject, the transition could be pending.

Philip
